# This file tells Netlify how to build Twelvety
# If you aren't using Netlify then you can delete this file

[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/sg-2024"
  to = "https://inkz.github.io/presentations/2024-bsides-singapore.pdf"
  status = 301
  force = false

[[redirects]]
  from = "/snowfroc"
  to = "https://inkz.github.io/presentations/2025-owasp-snowfroc.pdf"
  status = 301
  force = false

[[redirects]]
  from = "/bsides2025"
  to = "https://inkz.github.io/presentations/2025-bsides-seattle.pdf"
  status = 301
  force = false

[[redirects]]
  from = "/gh-webinar"
  to = "https://inkz.github.io/presentations/2025-gh-semgrep-webinar.pdf"
  status = 301
  force = false
  
[[redirects]]
  from = "/cyber-toronto"
  to = "https://inkz.github.io/presentations/2025-cyber-toronto.pdf"
  status = 301
  force = false
